#ifndef VERSION_H

#define THISBUILD "v0.1.1.39"

#define FIRMWARE_RELEASE_VER 0
#define FIRMWARE_MAJOR_VER 1
#define FIRMWARE_MINOR_VER 1
#define FIRMWARE_BUILD_NO 39

#define COMPILE_DATE __DATE__

#define COMPILE_TIME __TIME__


#endif // VERSION_H


